### ISSUE TITLE
Lumira Designer 2 SP02 (CLIENT_INFORMATION)

### ISSUE THREAD

**Issue by nloeblich** [org-scn-design-studio-community/lumiradesignercommunityext#20]
Hello Mike,

I hope you still interested in problems.
The SDK Component "CLIENT_INFORMATION" returns no result (-1 and 0) for function:
.getWindowWith();
.getWindowHeight();
.getOwnWith();
.getOwnHeight(); 

Thanks
Nico

**Comment by nloeblich** [comment]
[Lumira Demo.zip](https://github.com/org-scn-design-studio-community/lumiradesignercommunityext/files/1522876/Lumira.Demo.zip)
I have put an example into it.
Have a look in message during initialization!
GLOBAL_FUNCTION.FUNC_GET_

WINDOW

**Comment by mikezaschka** [comment]
I sadly cannot open the attached demo, since it's using additional components.
But the Client Information is working for me. It will return the above values if used during the onStartUp-event of your application, but when I access the information from within "On Size Change" of the Client Information component, everything works as expected.

**Comment by nloeblich** [comment]
Hello Mike,

I'm sorry that was my mistake.
You are right. I just used my code in a wrong Event.
As you mention I put code to "On Size Change".

Cheers
Nico
